
"""add product & offering tables

Revision ID: 2522b70097b6
Revises: ed8d1b97ee47
Create Date: 2025-07-05 08:00:39.542621+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2522b70097b6'
down_revision = 'ed8d1b97ee47'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='user_role_enum'),
               type_=sa.Enum('admin', 'user', name='user_role_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role_enum"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='user_role_enum', native_enum=False),
               type_=postgresql.ENUM('admin', 'user', name='user_role_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role_enum"))
    # ### end Alembic commands ###
