
"""universal company fields

Revision ID: 6d71f70e0fd2
Revises: 276906a3cd89
Create Date: 2025-07-05 00:35:35.946779+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d71f70e0fd2'
down_revision = '276906a3cd89'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.add_column('companies', sa.Column('industry', sa.String(length=128), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('mission', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('vision', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('values', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('size', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'extra')
    op.drop_column('companies', 'social_links')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'size')
    op.drop_column('companies', 'founded_year')
    op.drop_column('companies', 'values')
    op.drop_column('companies', 'vision')
    op.drop_column('companies', 'mission')
    op.drop_column('companies', 'tagline')
    op.drop_column('companies', 'logo')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'industry')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
